python extract_text.py 0 &
python extract_text.py 1 &
python extract_text.py 2 &
python extract_text.py 3 &
python extract_text.py 4 &
python extract_text.py 5 &
python extract_text.py 6 &
python extract_text.py 7 &
python extract_text.py 8 &
python extract_text.py 9 &
python extract_text.py 10 &
python extract_text.py 11 &
python extract_text.py 12 &
python extract_text.py 13 &
python extract_text.py 14 &
